words = [
    "ACK's",
    "CLI",
    "CWR",
    "DSCP",
    "ECE",
    "ECN",
    "FHS",
    "IFNAMSIZ",
    "IHL",
    "ISN",
    "MTU",
    "NUL",
    "POLLIN",
    "PSH",
    "SEG",
    "Swatinem",
    "TUNSETIFF",
    "UDP",
    "URG",
    "WND",
    "acked",
    "acking",
    "acks",
    "cksum",
    "clippy",
    "cov",
    "ctype",
    "datagram's",
    "datagrams",
    "dgram",
    "direnv",
    "distros",
    "dtolnay",
    "dumpcap",
    "envrc",
    "ifr",
    "ifreq",
    "inetutils",
    "ipv",
    "isspace",
    "lookups",
    "mins",
    "netcat",
    "netem",
    "nicknovitski",
    "nixbuild",
    "nixos",
    "nixpkgs",
    "nxt",
    "oldact",
    "oxalica",
    "pfd",
    "pkgs",
    "pollfd",
    "pthread",
    "rcv",
    "resends",
    "revents",
    "rto",
    "rustfmt",
    "rustup",
    "setcap",
    "sigaction",
    "sigemptyset",
    "signedness",
    "signum",
    "sigset",
    "snd",
    "struct's",
    "subslice",
    "syscall",
    "syscalls",
    "sysfs",
    "tshark",
    "typenet",
    "unacked",
    "untransmittable",
    "urandom",
    "userspace",
    "vtable",
    "wireshark",
    "xzf",
]
ignore_paths = [
    "Cargo.lock",
    "flake.lock",
]
ignore_patterns = [
    '\b[a-fA-F0-9]{64}\b',
    '\b0x[a-fA-F0-9_]{4,9}\b',
]
